<?php
declare(strict_types=1);


namespace Base;


use AssertTrait;
use Traits\ContainerAware;

final class ApiContext extends \Imbo\BehatApiExtension\Context\ApiContext
{
    use AssertTrait;
    use ContainerAware;

    protected $parameters;

    public function __construct(array $parameters = [])
    {
        $this->parameters = $parameters;
    }

    public function getResponseBody()
    {
        return parent::getResponseBody(); // TODO: Change the autogenerated stub
    }

}
